Add JAWSM
test262-fyi/data pull request #87
Opened 2024-12-14 03:40 UTC by drogus

It doesn't work yet, but I wanted to open a PR for troubleshooting

2024-12-16 21:42 UTC, linusg commented
You can't use CI for testing, it doesn't run any tests.

2024-12-16 23:34 UTC, drogus commented
@linusg yeah, I know, by troubleshooting I meant any comments from @CanadaHonk or someone else that knows more about the harness. I managed to make it work locally, so I think it's good to go.

2024-12-16 23:43 UTC, linusg requested changes

2024-12-16 23:43 UTC, linusg commented on scripts/engines/jawsm.sh
> +cargo build --release
Cargo can't handle "many cores, limited RAM", this risks OOMing the runner.

https://github.com/test262-fyi/test262.fyi/blob/753db7768f9d9e760b91361d2d399cd8b97a0677/scripts/engines/nova.sh#L9

2024-12-16 23:44 UTC, linusg requested changes
This needs more work, see https://github.com/test262-fyi/test262.fyi/commit/753db7768f9d9e760b91361d2d399cd8b97a0677 for an example of what needs changing.

2024-12-17 00:05 UTC, drogus commented
Thanks for the review @linusg, I fixed all the spots I found to be different than the example.

2024-12-18 11:52 UTC, drogus commented
Also, linking a corresponding PR in eshost: https://github.com/test262-fyi/eshost/pull/22

2025-09-01 16:12 UTC, linusg commented
Needs to be reworked for v2 (see #98), please open a new PR if still wanted

2025-09-01 16:12 UTC, closed without merging